# Optimized Build Stage
FROM ghcr.io/cirruslabs/flutter:stable AS build

# Copy project files
WORKDIR /app
COPY . .

# Pass build arguments
ARG BACKEND_URL

# Build for web
RUN flutter pub get
RUN flutter build web --release --dart-define=BACKEND_URL=$BACKEND_URL


# Stage 2: Serve with Nginx
# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
