// File generated by FlutterFire CLI.
// This file contains Firebase configuration for the app
// Note: Replace these with your actual Firebase project credentials

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UaUBDY0sMMFG8IlG2CDu5QLCWwwPX7E',
    appId: '1:1076739160583:web:8f150a29a20799f8b288a2',
    messagingSenderId: '1076739160583',
    projectId: 'demo1-7b8fb',
    authDomain: 'demo1-7b8fb.firebaseapp.com',
    storageBucket: 'demo1-7b8fb.firebasestorage.app',
    measurementId: 'G-R3786W8WHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGhQ8PNbfoa5iKQ9VregmLCbyQAFNBQ-c',
    appId: '1:1076739160583:android:a61a61f0b59c330cb288a2',
    messagingSenderId: '1076739160583',
    projectId: 'demo1-7b8fb',
    storageBucket: 'demo1-7b8fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKFP5aspjoldJ0DWamlW2Ooe1pa11cDfo',
    appId: '1:1076739160583:ios:d974732ffbbde8b7b288a2',
    messagingSenderId: '1076739160583',
    projectId: 'demo1-7b8fb',
    storageBucket: 'demo1-7b8fb.firebasestorage.app',
    iosBundleId: 'com.example.sepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKFP5aspjoldJ0DWamlW2Ooe1pa11cDfo',
    appId: '1:1076739160583:ios:d974732ffbbde8b7b288a2',
    messagingSenderId: '1076739160583',
    projectId: 'demo1-7b8fb',
    storageBucket: 'demo1-7b8fb.firebasestorage.app',
    iosBundleId: 'com.example.sepro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsH7ROIFxQsCS1V38wFaDcIm4jlWnMn48',
    appId: '1:1076739160583:web:35adce7eadf8f5e1b288a2',
    messagingSenderId: '1076739160583',
    projectId: 'demo1-7b8fb',
    authDomain: 'demo1-7b8fb.firebaseapp.com',
    storageBucket: 'demo1-7b8fb.firebasestorage.app',
    measurementId: 'G-X3NCGTYHS8',
  );

}